export const LOAD_MOVIE_LIST_INPROGRESS = "LOAD_MOVIE_LIST_INPROGRESS";
export const LOAD_MOVIE_LIST_SUCCESS = "LOAD_MOVIE_LIST_SUCCESS";
export const LOAD_MOVIE_LIST_FAILURE = "LOAD_MOVIE_LIST_FAILURE";
export const SORT_BY_EPISODE = "SORT_BY_EPISODE";
export const SORT_BY_YEAR = "SORT_BY_YEAR";